version: "3.8"
services:
  main_db:
    image: postgres:latest
    container_name: "${APP_NAME}_db"
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_USER_PASSWORD}
    volumes:
      - main_db:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
  redis:
    image: redis:7-alpine
    container_name: "${APP_NAME}_redis"
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis:/data
    ports:
      - "127.0.0.1:${REDIS_PORT}:6379"

volumes:
  main_db:
  redis:
