version: "1.0"
services:
  main_db:
    image: postgres:latest
    container_name: main_db
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_USER_PASSWORD}
    volumes:
      - main_db:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

volumes:
  main_db:
